# Es wird gelistet, welches netz mit welchem netz kommunizieren kann.
#
# Entscheidungshilfe zwischen backend und server: soll es von world angesprochen werden koennen?
#
#
# http://www.inf.fu-berlin.de/lehre/SS00/DS/folien/Firewalls+VPNs.pdf
klassifizierung:
  intern: intern, backend, server, world
  backend: backend, server, world
  server: backend, server, world
  world: server, world

Firmenwebserver:
  position: server, weil die Website von aussen ereichbar sein soll.
  anwendung: nginx
Webserver_im_Web:
  position: world, weil es nicht teil von der Firma ist.
  anwendung: nginx
SMTP: 
  position: server, weil email sowohl von aussen, als auch von innen versendet werden koennen.
  anwendung: postfix
IMAP: 
  position: server,weil emails von aussen, als auch von innen abgerufen werden sollen.  
  anwendung: dovecot2
Print-Server:
  position: client, warum sollte man von aussen drucken duerfen? nicht im backend, weil die drucker wahrscheinlich 
            im client-netz stehen. Wir muessten dann fuer die drucker zusaetzliche regeln einrichten.
  anwendung: CUPS
Interner_DNS:
  position: client,weil alle internen Rechnernamen und Ip-Adressen ohne externen Referenzen gepflegt werden
  anwendung: dnsmasq
Datenbank:
  position: backend, weil die datenbank hoechstwahrscheinlich ueber die server angesprochen werden soll,
            aber nicht direkt & offen im netz liegen soll.
  anwendung: postgres
NTP:
  position: backend, weil NTP hierarchisch aufgebaut ist und einen Verbindungsaufbau vornimmt. Es muss also nicht offen im netz
            liegen. Die Server erreichen diese dennoch um die aktuelle Zeit zu erhalten und die Klienten kommen auch ran. (Koennte aber auch server)
  anwendung: ntp

Fragen:
  - SMTP aufteilen in intern und extern?
    Pro: bessere trennung zwischen einfluss und ausfluss.
    Contra:
    Nein, weil es nur eine "Demilitarisierte Zone" gibt.
  - IMAP wirklich in intern hinein?
    Pro: Die immer vorliegenden Mails sind im 'intern' besser gesichert.
    Contra: Dann ist es nicht moeglich unterwegs(Im Web) via. IMAP die Mails zu ziehen.
  - Interner DNS wie in Folien in Client?
    Pro: Alle netzwerkkomponenten werden im Clientnetzwerk gesolved.
    Contra: Die server und backends koennen sich dann nicht gegenseitig solven.
